# NOTE(1): if the global stats are ever generated by the app again, we might
# no-longer need to have the total_area and protected_area attributes
namespace :import do
  desc 'import CSV data into database'
  task :habitats, [:csv_file] => [:environment] do
    habitats_config = YAML.load(File.open("#{Rails.root}/config/habitats.yml", 'r'))

    habitats_config['habitats'].each do |name, data|
      attributes = {
        title: data['title'],
        theme: data['theme'],
        poly_table: data['poly_table'],
        point_table: data['point_table'],
        wms_url: data['wms_url'],
        total_area: data['total_area'].to_f, # see NOTE(1)
        protected_area: data['protected_area'].to_f # see NOTE(1)
      }

      Habitat.find_or_create_by(name: data['name']).update_attributes(attributes)

      Rails.logger.info "#{name.capitalize} habitat created!"
    end
  end
end
