habitats:
  warmwater:
    name: 'coralreefs'
    title: 'Warm-water corals'
    theme: 'orange'
    wms_url: 'https://gis.unep-wcmc.org/arcgis/rest/services/marine/WCMC_008_CoralReefs_WMS/MapServer/export?transparent=true&format=png32&bbox={bbox-epsg-3857}&bboxSR=EPSG:3857&imageSR=EPSG:3857&size=256,256&f=image'
    total_area: 149887.00112183968
    protected_area: 62575.761695716465
  saltmarshes:
    name: 'saltmarshes'
    title: 'Saltmarshes'
    theme: 'green'
    wms_url: 'https://gis.unep-wcmc.org/arcgis/rest/services/marine/WCMC_027_Saltmarsh_WMS/MapServer/export?transparent=true&format=png32&bbox={bbox-epsg-3857}&bboxSR=EPSG:3857&imageSR=EPSG:3857&size=256,256&f=image'
    total_area: 224435.01599749923
    protected_area: 114235.68252213618
  mangroves:
    name: 'mangroves'
    title: 'Mangroves'
    theme: 'yellow'
    wms_url: 'https://gis.unep-wcmc.org/arcgis/rest/services/marine/WCMC_011_WorldAtlasMangroves_WMS/MapServer/export?transparent=true&format=png32&bbox={bbox-epsg-3857}&bboxSR=EPSG:3857&imageSR=EPSG:3857&size=256,256&f=image'
    total_area: 145690.84745655482
    protected_area: 63459.8096314046
  seagrasses:
    name: 'seagrasses'
    title: 'Seagrasses'
    theme: 'blue'
    wms_url: 'https://gis.unep-wcmc.org/arcgis/rest/services/marine/WCMC_013_014_Seagrass_WMS/MapServer/export?transparent=true&format=png32&bbox={bbox-epsg-3857}&bboxSR=EPSG:3857&imageSR=EPSG:3857&size=256,256&f=image'
    total_area: 321681.45199793996
    protected_area: 93427.42556799314
  coldcorals:
    name: 'coldcorals'
    title: 'Cold-water corals'
    theme: 'pink'
    wms_url: 'https://gis.unep-wcmc.org/arcgis/rest/services/marine/WCMC_001_ColdCorals2017_WMS/MapServer/export?transparent=true&format=png32&bbox={bbox-epsg-3857}&bboxSR=EPSG:3857&imageSR=EPSG:3857&size=256,256&f=image'
    total_area: 15335.158496840817
    protected_area: 4532.138887115459
