habitats:
  warmwater:
    name: 'coralreefs'
    title: 'Warm-water corals'
    theme: 'orange'
    wms_url: 'https://gis.unep-wcmc.org/arcgis/rest/services/marine/WCMC_008_CoralReefs_WMS/MapServer/export?transparent=true&format=png32&bbox={bbox-epsg-3857}&bboxSR=EPSG:3857&imageSR=EPSG:3857&size=256,256&f=image'
    total_area: 149886.974126351
    protected_area: 67498.1537285504
  saltmarshes:
    name: 'saltmarshes'
    title: 'Saltmarshes'
    theme: 'green'
    wms_url: 'https://gis.unep-wcmc.org/arcgis/rest/services/marine/WCMC_027_Saltmarsh_WMS/MapServer/export?transparent=true&format=png32&bbox={bbox-epsg-3857}&bboxSR=EPSG:3857&imageSR=EPSG:3857&size=256,256&f=image'
    total_area: 224435.075089817
    protected_area: 111454.965592792
  mangroves:
    name: 'mangroves'
    title: 'Mangroves'
    theme: 'yellow'
    wms_url: 'https://gis.unep-wcmc.org/arcgis/rest/services/marine/WCMC_011_WorldAtlasMangroves_WMS/MapServer/export?transparent=true&format=png32&bbox={bbox-epsg-3857}&bboxSR=EPSG:3857&imageSR=EPSG:3857&size=256,256&f=image'
    total_area: 135869.552270024
    protected_area: 58847.6773406482
  seagrasses:
    name: 'seagrasses'
    title: 'Seagrasses'
    theme: 'blue'
    wms_url: 'https://gis.unep-wcmc.org/arcgis/rest/services/marine/WCMC_013_014_Seagrass_WMS/MapServer/export?transparent=true&format=png32&bbox={bbox-epsg-3857}&bboxSR=EPSG:3857&imageSR=EPSG:3857&size=256,256&f=image'
    total_area: 314001.940552758
    protected_area: 83689.7720939699
  coldcorals:
    name: 'coldcorals'
    title: 'Cold-water corals'
    theme: 'pink'
    wms_url: 'https://gis.unep-wcmc.org/arcgis/rest/services/marine/WCMC_001_ColdCorals2017_WMS/MapServer/export?transparent=true&format=png32&bbox={bbox-epsg-3857}&bboxSR=EPSG:3857&imageSR=EPSG:3857&size=256,256&f=image'
    total_area: 15336.9752787556
    protected_area: 4511.04992438828

